CREATE TABLE `files` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `object_type` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `object_id` bigint(20) unsigned NOT NULL,
  `storage` enum('local','cloud') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'local',
  `title` varchar(150) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `path` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `filename` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `extension` varchar(5) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `mime_type` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `size` varchar(10) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `is_backed_up` tinyint(1) NOT NULL DEFAULT '0',
  `is_backed_up_at` timestamp NULL DEFAULT NULL,
  `is_file_missing` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`),
  KEY `object_type` (`object_type`),
  KEY `object_id` (`object_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;